---
name: pre-commit-check
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /usr/local/Homebrew/Library
          key: homebrew-library|${{ hashFiles('usr/local/Homebrew/Library') }}
          restore-keys: |
            homebrew-library
      - uses: actions/cache@v1
        with:
          path: /usr/local/Cellar
          key: homebrew-cellar|${{ hashFiles('usr/local/Homebrew/Library') }}
          restore-keys: |
            homebrew-cellar
      - name: Install prerequisites
        run: ./bin/install-macos.sh
      - name: initiallize Terraform
        run: terraform init --backend=false
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit
      - name: pre-commit run all
        run: |
          pre-commit run -a
        env:
          AWS_DEFAULT_REGION: us-east-1
          SKIP: terraform_tflint_deep
